In [1]:
import pandas as pd
import numpy as np

In [9]:
df_1 = pd.DataFrame([[1,2,3], [2,5,4]], columns=['a', 'b', 'c'])
df_2 = pd.DataFrame([[2,3,4], [3,6,2]], columns=['a', 'b', 'c'])

In [10]:
df = pd.MultiIndex.from_product([df_1, df_2], names=['first', 'second'])

In [11]:
df

MultiIndex(levels=[['a', 'b', 'c'], ['a', 'b', 'c']],
           labels=[[0, 0, 0, 1, 1, 1, 2, 2, 2], [0, 1, 2, 0, 1, 2, 0, 1, 2]],
           names=['first', 'second'])

In [12]:
df.first

AttributeError: 'MultiIndex' object has no attribute 'first'

In [13]:
iterables = [['negative', 'positive'], ['a', 'b', 'c']]
index = pd.MultiIndex.from_product(iterables, names=['category', 'feature'])

In [14]:
df = pd.DataFrame(np.random.randn(3, 6), columns=index)
df

category  negative                      positive
feature          a         b         c         a         b         c
0        -2.886369  0.749247  1.892146  1.358855 -2.127000 -0.138308
1         0.885476 -0.066666  2.065488  0.224332  0.186758  0.315603
2        -0.656336  0.255354  0.024989  0.665372  0.454394 -2.160862

In [15]:
df.iloc[0]

category  feature
negative  a         -2.886369
          b          0.749247
          c          1.892146
positive  a          1.358855
          b         -2.127000
          c         -0.138308
Name: 0, dtype: float64

In [16]:
df = df.append(pd.DataFrame([[1,2,3,5,6,7]], columns=index))

In [21]:
df

category index  negative                      positive
feature                a         b         c         a         b         c
0            0 -2.886369  0.749247  1.892146  1.358855 -2.127000 -0.138308
1            1  0.885476 -0.066666  2.065488  0.224332  0.186758  0.315603
2            2 -0.656336  0.255354  0.024989  0.665372  0.454394 -2.160862
3            0  1.000000  2.000000  3.000000  5.000000  6.000000  7.000000

In [3]:
insert = {'negative': {'a':1, 'b':2, 'c':3}, 'positive': {'a':4, 'b':5, 'c':6}}
reform = {(outerKey, innerKey): values for outerKey, innerDict in insert.items() for innerKey, values in innerDict.items()}
df.append(pd.DataFrame(insert, index=[0]))

NameError: name 'df' is not defined

In [104]:
reform

{('negative', 'a'): 1,
 ('negative', 'b'): 2,
 ('negative', 'c'): 3,
 ('positive', 'a'): 4,
 ('positive', 'b'): 5,
 ('positive', 'c'): 6}

In [91]:
reform = {(outerKey, innerKey): values for outerKey, innerDict in insert.items() for innerKey, values in innerDict.items()}
reform

{('negative', 'a'): 1,
 ('negative', 'b'): 1,
 ('negative', 'c'): 1,
 ('positive', 'a'): 1,
 ('positive', 'b'): 1,
 ('positive', 'c'): 1}

In [22]:
import draco.learn.preprocess
draco.learn.preprocess.load_data()

    index  negative                                                            \
          add_count agg_dim aggregate aggregate_group_by_raw area_raw bar_raw
0       0         0       0         0                      0        0       0
1       0         0       0         0                      0        0       0
2       0         0       0         1                      0        0       0
3       0         0       0         1                      0        0       0
4       0         0       0         1                      0        0       0
5       0         0       0         1                      0        0       0
6       0         0       0         1                      0        0       0
7       0         0       0         1                      0        0       0
8       0         0       0         1                      0        0       0
9       0         0       0         1                      0        0       0
10      0         0       0         2                      0        0       0
11      0         0       0         2                      0        0       0
12      0         0       0         2                      0        0       0
13      0         0       0         2                      0        0       0
14      0         0       0         1                      0        0       0
15      0         0       0         1                      0        0       0
16      0         0       0         1                      0        0       0
17      0         0       0         1                      0        0       0
18      0         0       0         1                      0        0       0
19      0         0       0         1                      0        0       0
20      0         0       0         1                      0        0       0
21      0         0       0         1                      0        0       0
22      0         0       0         2                      0        0       0
23      0         0       0         2                      0        0       0
24      0         0       0         1                      0        0       0
25      0         0       0         1                      0        0       0
26      0         0       0         1                      0        0       0
27      0         0       0         1                      0        0       0
28      0         0       0         2                      0        0       0
29      0         0       0         1                      0        0       0
..    ...       ...     ...       ...                    ...      ...     ...
764     0         0       0         1                      0        0       0
765     0         0       0         2                      0        0       0
766     0         0       0         2                      0        0       0
767     0         0       0         1                      0        0       0
768     0         0       0         2                      0        0       0
769     0         0       0         1                      0        0       0
770     0         0       0         1                      0        0       0
771     0         0       0         1                      0        0       0
772     0         0       0         1                      0        0       0
773     0         0       0         1                      0        0       0
774     0         0       0         1                      0        0       0
775     0         0       0         1                      0        0       0
776     0         0       0         2                      0        0       0
777     0         0       0         1                      0        0       0
778     0         0       0         2                      0        0       0
779     0         0       0         2                      0        0       0
780     0         0       0         1                      0        0       0
781     0         0       0         1                      0        0       0
782     0         0       0         2                      0        0       0
783     0         0       0         2                      0        0       0
784     0         0       0         1                      0        0       0
785     0         0       0         2                      0        0       0
786     0         0       0         2                      0        0       0
787     0         0       0         1                      0        0       0
788     0         0       0         1                      0        0       0
789     0         0       0         2                      0        0       0
790     0         0       0         1                      0        0       0
791     0         0       0         1                      0        0       0
792     0         0       0         1                      0        0       0
793     0         0       0         1                      0        0       0

                                                     ...      positive  \
    bar_size bin_cardinality categorical_cardinality ...  same_field_4
0          0               0                       0 ...             0
1          0               0                       0 ...             0
2          0               0                       0 ...             0
3          0               0                       0 ...             0
4          0               0                       0 ...             0
5          0               0                       0 ...             0
6          0               0                       0 ...             0
7          0               0                       0 ...             0
8          0               0                       0 ...             0
9          0               0                       0 ...             0
10         0               0                       0 ...             0
11         0               0                       0 ...             0
12         0               0                       0 ...             0
13         0               0                       0 ...             0
14         0               0                       0 ...             0
15         0               0                       0 ...             0
16         0               0                       0 ...             0
17         0               0                       0 ...             0
18         0               0                       0 ...             0
19         0               0                       0 ...             0
20         0               0                       0 ...             0
21         0               0                       0 ...             0
22         0               0                       0 ...             0
23         0               0                       0 ...             0
24         0               0                       0 ...             0
25         0               0                       0 ...             0
26         0               0                       0 ...             0
27         0               0                       0 ...             0
28         0               0                       0 ...             0
29         0               0                       0 ...             0
..       ...             ...                     ... ...           ...
764        0               0                       0 ...             0
765        0               0                       0 ...             0
766        0               0                       0 ...             0
767        0               0                       0 ...             0
768        0               0                       0 ...             0
769        0               0                       0 ...             0
770        0               0                       0 ...             0
771        0               0                       0 ...             0
772        0               0                       0 ...             0
773        0               0                       0 ...             0
774        0               0                       0 ...             0
775        0               0                       0 ...             0
776        0               0                       0 ...             0
777        0               0                       0 ...             0
778        0               0                       0 ...             0
779        0               0                       0 ...             0
780        0               0                       0 ...             0
781        0               0                       0 ...             0
782        0               0                       0 ...             0
783        0               0                       0 ...             0
784        0               0                       0 ...             0
785        0               0                       0 ...             0
786        0               0                       0 ...             0
787        0               0                       0 ...             0
788        0               0                       0 ...             0
789        0               0                       0 ...             0
790        0               0                       0 ...             0
791        0               0                       0 ...             0
792        0               0                       0 ...             0
793        0               0                       0 ...             0

                                                                      \
    same_field_gte5 shape_cardinality tick_size type_n type_o type_q
0                 0                 0         0      0      0      2
1                 0                 0         0      0      0      2
2                 0                 0         0      1      0      3
3                 0                 0         0      1      0      3
4                 0                 0         0      1      0      3
5                 0                 0         0      1      0      3
6                 0                 0         0      1      0      3
7                 0                 0         0      1      0      3
8                 0                 0         0      1      0      3
9                 0                 0         0      1      0      3
10                0                 0         0      1      0      3
11                0                 0         0      1      0      3
12                0                 0         0      1      0      3
13                0                 0         0      1      0      3
14                0                 0         0      1      0      3
15                0                 0         0      1      0      3
16                0                 0         0      1      0      3
17                0                 0         0      1      0      3
18                0                 0         0      1      0      3
19                0                 0         0      1      0      3
20                0                 0         0      1      0      3
21                0                 0         0      1      0      3
22                0                 0         0      1      0      3
23                0                 0         0      1      0      3
24                0                 0         0      1      0      3
25                0                 0         0      1      0      3
26                0                 0         0      1      0      3
27                0                 0         0      1      0      3
28                0                 0         0      1      0      3
29                0                 0         0      1      0      3
..              ...               ...       ...    ...    ...    ...
764               0                 0         0      1      0      3
765               0                 0         0      1      0      3
766               0                 0         0      1      0      3
767               0                 0         0      1      0      3
768               0                 0         0      1      0      3
769               0                 0         0      1      0      3
770               0                 0         0      1      0      3
771               0                 0         0      1      0      3
772               0                 0         0      1      0      3
773               0                 0         0      1      0      3
774               0                 0         0      1      0      3
775               0                 0         0      1      0      3
776               0                 0         0      1      0      3
777               0                 0         0      1      0      3
778               0                 0         0      1      0      3
779               0                 0         0      1      0      3
780               0                 0         0      1      0      3
781               0                 0         0      1      0      3
782               0                 0         0      1      0      3
783               0                 0         0      1      0      3
784               0                 0         0      1      0      3
785               0                 0         0      1      0      3
786               0                 0         0      1      0      3
787               0                 0         0      1      0      3
788               0                 0         0      1      0      3
789               0                 0         0      1      0      3
790               0                 0         0      1      0      3
791               0                 0         0      1      0      3
792               0                 0         0      1      0      3
793               0                 0         0      1      0      3


    vertical_dot x_y_raw zero
0              2       0    2
1              0       0    2
2              2       0    1
3              2       0    1
4              2       0    1
5              2       0    1
6              2       0    1
7              2       0    1
8              2       0    1
9              2       0    2
10             2       0    2
11             2       0    2
12             2       0    2
13             2       0    1
14             2       0    1
15             2       0    1
16             2       0    1
17             2       0    1
18             2       0    1
19             2       0    1
20             2       0    1
21             2       0    2
22             2       0    2
23             2       0    2
24             2       0    1
25             2       0    1
26             2       0    1
27             2       0    2
28             2       0    1
29             2       0    2
..           ...     ...  ...
764            2       0    2
765            2       0    2
766            2       0    1
767            2       0    2
768            2       0    1
769            2       0    1
770            2       0    1
771            2       0    1
772            2       0    1
773            2       0    1
774            2       0    1
775            2       0    2
776            2       0    1
777            2       0    2
778            2       0    2
779            2       0    1
780            2       0    1
781            2       0    2
782            2       0    1
783            2       0    1
784            2       0    2
785            2       0    2
786            2       0    1
787            2       0    1
788            2       0    2
789            2       0    1
790            2       0    1
791            2       0    1
792            2       0    1
793            2       0    1

[794 rows x 161 columns]

In [2]:
pd.DataFrame(index=range(10), columns=['a', 'b'])

     a    b
0  NaN  NaN
1  NaN  NaN
2  NaN  NaN
3  NaN  NaN
4  NaN  NaN
5  NaN  NaN
6  NaN  NaN
7  NaN  NaN
8  NaN  NaN
9  NaN  NaN

In [4]:
x = np.unique([1,2,3])

In [5]:
x.index(2)

AttributeError: 'numpy.ndarray' object has no attribute 'index'